job('First-Maven-Project-Via-DSL') {
    description("First Maven job generated by the DSL on ${new Date()}, the project is a small Maven project hosted on github")
    scm {
        git("https://github.com/jdochert/single-module.git", '*/main')
    }
    triggers {
        scm('* * * * *')
    }
    steps {
	maven {
		mavenInstallation('Local Maven')
	}
	maven('clean package')
	
    }
    publishers {
        //archive the war file generated
        archiveArtifacts '**/*.jar'
    }
}
